name: Unit Tests

on:
  push:
    branches:
      - main  # Adjust the branch name to your specific branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8  # Adjust to your Python version (e.g., "3.8")

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have dependencies listed in a requirements.txt file

    - name: Run unit tests and coverage
      run: |
        coverage run -m unittest discover -s src/test -p '*_tests.py'  # Assuming your tests are in a "tests" directory and are called *_tests.py

    - name: generate coverage report
      run: |
        coverage html

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      



