name: Automated Unit Tests

on:
  push:
    branches:
      - main  # Adjust the branch name to your specific branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Adjust to your Python version (e.g., "3.8")

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have dependencies listed in a requirements.txt file

    - name: Run unit tests
      run: |
        python -m unittest discover src/test -p *test*.py  # Assuming your tests are in a "tests" directory and are called *test*.py

